export const TOPICS = [
  { name: '' },
  { name: 'Mathematics' },
  { name: 'Literature' },
  { name: 'History' },
  { name: 'Physics' },
  { name: 'Chemistry' },
  { name: 'Civic Education' },
  { name: 'Fine Art' },
  { name: 'Engineering' },
  { name: 'English' },
  { name: 'Informatics' },
  { name: 'Technology' },
  { name: 'Biology' },
  { name: 'Accounting' },
  { name: 'Business Administration' },
  { name: 'Business English' },
  { name: 'Chemical Engineering' },
  { name: 'Commercial Law' },
  { name: 'Control Engineering' },
  { name: 'Development economics' },
  { name: 'E-Commerce Administration' },
  { name: 'Economics' },
  { name: 'Electrical Engineering' },
  { name: 'Environment Engineering' },
  { name: 'Finance and Banking' },
  { name: 'Food Technology' },
  { name: 'Hotel Management' },
  { name: 'Information Technology' },
  { name: 'International Payment' },
  { name: 'International Trade' },
  { name: 'Marketing' },
  { name: 'Materials Science' },
  { name: 'Mechanical Engineering' },
  { name: 'Mechanics' },
  { name: 'Nuclear Engineering' },
  { name: 'Public Economics' },
  { name: 'Telecommunication' },
  { name: 'Trade Marketing' },
  { name: 'Trading Economics' },
  { name: 'Transportation Engineering' },
  { name: 'Other' },
]
